const WHITE = '#FFFFFF';
const BLACK = '0a0a0a';
const BACKGROUND = '#fbfcfd';
const FOREGROUND = '#222831';

const BASE_100 = BACKGROUND;
const BASE_150 = '#f4f7fa';
const BASE_200 = '#f1f5f9';
const BASE_300 = '#e2ebf3';
const BASE_CONTENT = FOREGROUND;

const PRIMARY = '#222831';
const PRIMARY_FOREGROUND = '#f2f5f8';
const SECONDARY = '#393E46';
const SECONDARY_FOREGROUND = '#f2f5f8';
const SECONDARY_LIGHT = '#9DB2BF';

const CARD = WHITE;
const CARD_FOREGROUND = BLACK;
const POPOVER = BACKGROUND;
const POPOVER_FOREGROUND = BLACK;

const MUTED = '#f5f5f5';
const MUTED_FOREGROUND = '#737373';
const ACCENT = '#00ADB5';
const ACCENT_FOREGROUND = WHITE;
const DESTRUCTIVE = '#f31260';
const DESTRUCTIVE_FOREGROUND = WHITE;
const SUCCESS = '#17c964';
const SUCCESS_FOREGROUND = WHITE;
const WARNING = '#f5a524';
const WARNING_FOREGROUND = WHITE;

const BORDER = '#e5e5e5';
const INPUT = '#e5e5e5';
const RING = BLACK;

const CHART_1 = '#e76e50';
const CHART_2 = '#2a9d90';
const CHART_3 = '#274754';
const CHART_4 = '#e8c468';
const CHART_5 = '#f4a462';

const colors = {
  WHITE,
  BACKGROUND,
  FOREGROUND,
  BASE_100,
  BASE_150,
  BASE_200,
  BASE_300,
  BASE_CONTENT,
  PRIMARY,
  PRIMARY_FOREGROUND,
  SECONDARY,
  SECONDARY_FOREGROUND,
  SECONDARY_LIGHT,
  CARD,
  CARD_FOREGROUND,
  POPOVER,
  POPOVER_FOREGROUND,
  MUTED,
  MUTED_FOREGROUND,
  ACCENT,
  ACCENT_FOREGROUND,
  DESTRUCTIVE,
  DESTRUCTIVE_FOREGROUND,
  SUCCESS,
  SUCCESS_FOREGROUND,
  WARNING,
  WARNING_FOREGROUND,
  BORDER,
  INPUT,
  RING,
  CHART_1,
  CHART_2,
  CHART_3,
  CHART_4,
  CHART_5,
};

export { colors };
